/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JfTela.java
 *
 * Created on 19/09/2011, 17:23:21
 */

package telas.vo;

@SuppressWarnings("serial")
public class MontaSqlSimplesVO extends javax.swing.JDialog {

	/** Creates new form JfTela */
	public MontaSqlSimplesVO() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		grupoDeSQL = new javax.swing.ButtonGroup();
		JpTela = new javax.swing.JPanel();
		TxtNomeBook = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		rbInsert = new javax.swing.JRadioButton();
		rbSelect = new javax.swing.JRadioButton();
		rbUpdate = new javax.swing.JRadioButton();
		rbCursor = new javax.swing.JRadioButton();
		jLabel3 = new javax.swing.JLabel();
		rbDelete = new javax.swing.JRadioButton();
		cbCarregarCBL = new javax.swing.JCheckBox();
		btnPesq = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Gerador SQL Simples");

		jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel1.setText("Nome do Book: ");

		jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel2.setText("Carregar DCLGEN");

		grupoDeSQL.add(rbInsert);
		rbInsert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		rbInsert.setText("Insert");

		grupoDeSQL.add(rbSelect);
		rbSelect.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		rbSelect.setText("Select");

		grupoDeSQL.add(rbUpdate);
		rbUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		rbUpdate.setText("Update");

		grupoDeSQL.add(rbCursor);
		rbCursor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		rbCursor.setText("Cursor");

		jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel3.setText("Selecione ");

		grupoDeSQL.add(rbDelete);
		rbDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		rbDelete.setText("Delete");

		cbCarregarCBL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		cbCarregarCBL.setText("Carregado");

		btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/telas/gui/icones/iconePesquisar.gif"))); // NOI18N

		javax.swing.GroupLayout JpTelaLayout = new javax.swing.GroupLayout(
				JpTela);
		JpTela.setLayout(JpTelaLayout);
		JpTelaLayout
				.setHorizontalGroup(JpTelaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								JpTelaLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												JpTelaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addGroup(
																JpTelaLayout
																		.createSequentialGroup()
																		.addGroup(
																				JpTelaLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								TxtNomeBook,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								99,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				JpTelaLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								JpTelaLayout
																										.createSequentialGroup()
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jLabel2))
																						.addGroup(
																								JpTelaLayout
																										.createSequentialGroup()
																										.addGap(
																												17,
																												17,
																												17)
																										.addComponent(
																												btnPesq,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												25,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												cbCarregarCBL))))
														.addGroup(
																JpTelaLayout
																		.createSequentialGroup()
																		.addGroup(
																				JpTelaLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								rbInsert)
																						.addComponent(
																								rbDelete))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				JpTelaLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								rbCursor)
																						.addGroup(
																								JpTelaLayout
																										.createSequentialGroup()
																										.addComponent(
																												rbSelect)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												rbUpdate)))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		JpTelaLayout
				.setVerticalGroup(JpTelaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								JpTelaLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												JpTelaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																30,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																32,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												JpTelaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																JpTelaLayout
																		.createSequentialGroup()
																		.addGroup(
																				JpTelaLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								TxtNomeBook,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								btnPesq,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								25,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				35,
																				35,
																				35)
																		.addComponent(
																				jLabel3))
														.addComponent(
																cbCarregarCBL))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												JpTelaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(rbInsert)
														.addComponent(rbSelect)
														.addComponent(rbUpdate))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												JpTelaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(rbDelete)
														.addComponent(rbCursor))
										.addGap(193, 193, 193)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						JpTela, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						JpTela, javax.swing.GroupLayout.PREFERRED_SIZE, 195,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(12, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MontaSqlSimplesVO().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel JpTela;
	private javax.swing.JTextField TxtNomeBook;
	private javax.swing.JButton btnPesq;
	private javax.swing.ButtonGroup grupoDeSQL;
	private javax.swing.JCheckBox cbCarregarCBL;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JRadioButton rbCursor;
	private javax.swing.JRadioButton rbInsert;
	private javax.swing.JRadioButton rbUpdate;
	private javax.swing.JRadioButton rbDelete;
	private javax.swing.JRadioButton rbSelect;
	// End of variables declaration//GEN-END:variables

}
